### ISSUE TITLE
r0 for the Application Services API

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-doc#1333]
Tracking issue for all the tasks that need to be completed for an r0 release of the AS API spec:
### Required
- [x] https://github.com/matrix-org/matrix-doc/issues/1325 AppServices: We need to specify the API endpoints under Querying - https://github.com/matrix-org/matrix-doc/pull/1537
- [x] https://github.com/matrix-org/matrix-doc/issues/1323 AS traffic rate-limiting
- [x] https://github.com/matrix-org/matrix-doc/issues/1307 AppServices: Document how filterings events work - https://github.com/matrix-org/matrix-doc/pull/1533
- [x] https://github.com/matrix-org/matrix-doc/issues/1296 AppServices: Document client-server requests omitting user_id param - https://github.com/matrix-org/matrix-doc/pull/1534
- [x] https://github.com/matrix-org/matrix-doc/issues/1294  'age' field should be in unsigned - https://github.com/matrix-org/matrix-doc/pull/1552
- [x] https://github.com/matrix-org/matrix-doc/issues/1272 Document Appservice Directories - https://github.com/matrix-org/matrix-doc/pull/1554
- [x] https://github.com/matrix-org/matrix-doc/issues/1271 Document Thirdparty AS Endpoints
- [x] https://github.com/matrix-org/matrix-doc/issues/1269 AppServices: Why do events sent to AS's use "user_id", whereas events use "sender" - https://github.com/matrix-org/matrix-doc/pull/1552
- [x] https://github.com/matrix-org/matrix-doc/pull/1262 Document new application service registration file options 
- [x] https://github.com/matrix-org/matrix-doc/issues/800 Remove lies from AS API spec about /_matrix/app/r0/alias and /_matrix/app/r0/user - https://github.com/matrix-org/matrix-doc/pull/1537
### Nice to haves
- [ ] https://github.com/matrix-org/matrix-doc/issues/1306 Proposal to filter out traffic to Appservices based on filters 

(Disclaimer: This is not yet a complete list, but a roundup of the issues we know that need to be completed so far)

**Comment by non-Jedi** [comment]
#800 should also be fixed before r0 release imo.

**Comment by Half-Shot** [comment]
@non-Jedi Good shout. Added

**Comment by turt2live** [comment]
Have updated the original post to better reflect the current state of affairs. The linked project (https://github.com/matrix-org/matrix-doc/projects/1) is a living document for all the specs, although this issue is still useful to keep track of all things appservice.

Still not entirely comfortable with removing the `[WIP]` tag though - I haven't done any additional prioritization to the list.

**Comment by Half-Shot** [comment]
I'd like to see these solved before r0:
- https://github.com/matrix-org/matrix-doc/issues/1394

**Comment by turt2live** [comment]
Just an update: #1394 has been closed in favour of #1585 due to #1586. #1323 has been closed (this was missed previously), and #1294 is being addressed by #1558. 

In addition, before an r0 can be cut we need a defined release process (https://github.com/matrix-org/matrix-doc/pull/1521) and the r0 prep to land (https://github.com/matrix-org/matrix-doc/pull/1555).
