### ISSUE TITLE
Federation API r0 megathread

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#1464]
This is a list of all the endpoints that are currently listed as "federation" (server-to-server), but have not been specced. Follow this issue for updates to the plan and progress.

----

## "Ambitious goal"
This all the stuff that qualifies for the running-name of "Travis' ambitious goal". Targeting very early August for spec.

Sections (review&fix):
* [x] PDUs and EDUs - https://github.com/matrix-org/matrix-doc/pull/1463
* [x] Server Discovery - https://github.com/matrix-org/matrix-doc/issues/1161, https://github.com/matrix-org/matrix-doc/pull/1479
* [x] State resolution
* [x] Authentication - https://github.com/matrix-org/matrix-doc/pull/1481
* [x] Presence - https://github.com/matrix-org/matrix-doc/pull/1482
* [x] Signing
* [x] General cleanup of sections - https://github.com/matrix-org/matrix-doc/pull/1478
* [x] Typing notifications - https://github.com/matrix-org/matrix-doc/pull/1483
* [x] Read receipts - https://github.com/matrix-org/matrix-doc/pull/1484

Endpoints:
* [x] `PUT /send/$txnId` - https://github.com/matrix-org/matrix-doc/pull/1461
* [x] ~~`GET /pull`~~ Unused endpoint
* [x] `GET /event/$eventId` - https://github.com/matrix-org/matrix-doc/pull/1472
* [x] `GET /state/$context` - https://github.com/matrix-org/matrix-doc/pull/1472
* [x] `GET /state_ids/$roomId` - https://github.com/matrix-org/matrix-doc/issues/1451, https://github.com/matrix-org/matrix-doc/pull/1472
* [x] `GET /backfill/$context` - https://github.com/matrix-org/matrix-doc/pull/1469
* [x] `GET /query/$queryType` - https://github.com/matrix-org/matrix-doc/issues/1404, https://github.com/matrix-org/matrix-doc/pull/1443
* [x] `GET /make_join/$context/$userId` - https://github.com/matrix-org/matrix-doc/pull/1428
* [x] `GET /make_leave/$context/$userId` - https://github.com/matrix-org/matrix-doc/issues/1401, https://github.com/matrix-org/matrix-doc/pull/1455
* [x] `PUT /send_leave/$roomId/$eventId` - https://github.com/matrix-org/matrix-doc/issues/1401, https://github.com/matrix-org/matrix-doc/pull/1455
* [x] `PUT /send_join/$roomId/$eventId` - https://github.com/matrix-org/matrix-doc/pull/1428
* [x] `PUT /invite/$context/$eventId` - https://github.com/matrix-org/matrix-doc/pull/1450
* [x] `GET /event_auth/$context/$eventId` - https://github.com/matrix-org/matrix-doc/issues/1274, https://github.com/matrix-org/matrix-doc/pull/1475
* [x] `POST /query_auth/$context/$eventId` - https://github.com/matrix-org/matrix-doc/pull/1475
* [x] `POST /get_missing_events/$roomId` - https://github.com/matrix-org/matrix-doc/issues/1385, https://github.com/matrix-org/matrix-doc/pull/1469
* [x] `GET /publicRooms` - https://github.com/matrix-org/matrix-doc/pull/1477
* [x] `GET /version`
* [x] `GET /key/v2/query/$serverName/$keyId` - https://github.com/matrix-org/matrix-doc/pull/1423
* [x] `POST /key/v2/query` - https://github.com/matrix-org/matrix-doc/pull/1423
* [x] `GET /key/v2/server/$keyId` - https://github.com/matrix-org/matrix-doc/pull/1423

## Media/Content Repository
Targeting August for spec. 

Issues:
* https://github.com/matrix-org/matrix-doc/issues/1341
* How to download content from remotes - https://github.com/matrix-org/matrix-doc/pull/1493

## Third party identifiers 
Targeting early August for spec. 

Issues:
* https://github.com/matrix-org/matrix-doc/issues/1366
* https://github.com/matrix-org/matrix-doc/issues/1476

Endpoints:
* [x] `PUT /exchange_third_party_invite/$roomId` - https://github.com/matrix-org/matrix-doc/pull/1505
* [x] `POST /3pid/onbind` - https://github.com/matrix-org/matrix-doc/issues/1422, https://github.com/matrix-org/matrix-doc/pull/1505

## End-to-end encryption
Targeting early August for spec (synchronized with client/server documentation).

Issues:
* https://github.com/matrix-org/matrix-doc/issues/501

Endpoints:
* [x] `POST /user/keys/query` - https://github.com/matrix-org/matrix-doc/issues/1438
* [x] `GET /user/devices/$userId` - https://github.com/matrix-org/matrix-doc/issues/1438
* [x] `POST /user/keys/claim` - https://github.com/matrix-org/matrix-doc/issues/1438

**The device list stuff (https://github.com/matrix-org/matrix-doc/issues/1212) is fairly subtle and would need to be specced alongside this, i suspect (but should be a matter of porting the necessary stuff out of the prop and into the spec) --matthew**

## OpenID
Targeting August for spec (synchronized with client/server documentation).

Issues:
* https://github.com/matrix-org/matrix-doc/issues/857
* ~~https://github.com/matrix-org/matrix-doc/issues/1115~~

Endpoints:
* [x] `GET /openid/userinfo` - https://github.com/matrix-org/matrix-doc/pull/1494

## ~~Groups~~
Targeting August for spec (synchronized with client/server documentation).

*Note: Groups have been cut from the r0 release, and will be worked out post-r0*

Issues:
* https://github.com/matrix-org/matrix-doc/issues/971

Endpoints:
* `GET /groups/$groupId/profile`
* `POST /groups/$groupId/profile`
* `GET /groups/$groupId/summary`
* `GET /groups/$groupId/rooms`
* `POST /groups/$groupId/room/$roomId`
* `DELETE /groups/$groupId/room/$roomId`
* `POST /groups/$groupId/room/$roomId/config/$configKey`
* `GET /groups/$groupId/users`
* `GET /groups/$groupId/invited_users`
* `POST /groups/$groupId/users/$userId/invite`
* `POST /groups/$groupId/users/$userId/accept_invite`
* `POST /groups/$groupId/users/$userId/join`
* `POST /groups/$groupId/users/$userId/remove`
* `POST /groups/local/$groupId/users/$userId/invite`
* `POST /groups/local/$groupId/users/$userId/remove`
* `POST /groups/$groupId/renew_attestation/$userId`
* `POST /groups/$groupId/summary/rooms/$roomId`
* `POST /groups/$groupId/summary/categories/$category/rooms/$roomId`
* `DELETE /groups/$groupId/summary/rooms/$roomId`
* `DELETE /groups/$groupId/summary/categories/$category/rooms/$roomId`
* `GET /groups/$groupdId/categories`
* `GET /groups/$groupId/categories/$category`
* `POST /groups/$groupId/categories/$category`
* `DELETE /groups/$groupId/categories/$category`
* `GET /groups/$groupId/roles`
* `GET /groups/$groupId/roles/$roleId`
* `POST /groups/$groupId/roles/$roleId`
* `DELETE /groups/$groupId/roles/$roleId`
* `POST /groups/$groupId/summary/users/$userId`
* `POST /groups/$groupId/summary/roles/$roleId/users/$userId`
* `DELETE /groups/$groupId/summary/users/$userId`
* `DELETE /groups/$groupId/summary/roles/$roleId/users/$userId`
* `POST /get_groups_publicised`
* `PUT /groups/$groupId/settings/m.join_policy`

**Comment by uhoreg** [comment]
Most of E2E should be covered by https://github.com/matrix-org/matrix-doc/pull/1284 and https://github.com/matrix-org/matrix-doc/pull/1420

**Comment by turt2live** [comment]
As far as I can tell, both of those only cover the client/server side of things. It'd be awesome if they also covered the s2s side too :)

**Comment by uhoreg** [comment]
Ah, right.  Yes, they're only CS.

**Comment by turt2live** [comment]
I've updated the OP: Everything is done except for groups. Groups are being considered post-r0 pending some potential changes. This issue is now a placeholder for "we need to actually cut a release".

**Comment by turt2live** [comment]
The reminder for actually cutting an r0 is now at https://github.com/matrix-org/matrix-doc/issues/1805
