### ISSUE TITLE
GDPR

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#1512]
This is all the issues for GDPR-related things.

* [ ] #1288  - `erase` param on `/deactivate`
* [ ] #1280 - communicating erasure over federation
* [ ] #1254 - error codes for trying to leave the "server notices" room (feature introduced as part of GDPR, not strictly related)
* [ ] #1252 - consent error
* [ ] #1228 - removing mxids from events
* [ ] #701 - auth for media repo
