### ISSUE TITLE
Groups

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#1513]
This is for all the groups/communities related issues.

* [ ] #1222 - pushing updates to clients
* [ ] #1217 - visibility of members
* [ ] ~~#1215~~ https://github.com/matrix-org/matrix-doc/pull/1772 - groups as rooms
* [ ] #1214 - flair
* [ ] #971 - most of the groups documentation

**Comment by turt2live** [comment]
Endpoints:
* `GET /groups/$groupId/profile`
* `POST /groups/$groupId/profile`
* `GET /groups/$groupId/summary`
* `GET /groups/$groupId/rooms`
* `POST /groups/$groupId/room/$roomId`
* `DELETE /groups/$groupId/room/$roomId`
* `POST /groups/$groupId/room/$roomId/config/$configKey`
* `GET /groups/$groupId/users`
* `GET /groups/$groupId/invited_users`
* `POST /groups/$groupId/users/$userId/invite`
* `POST /groups/$groupId/users/$userId/accept_invite`
* `POST /groups/$groupId/users/$userId/join`
* `POST /groups/$groupId/users/$userId/remove`
* `POST /groups/local/$groupId/users/$userId/invite`
* `POST /groups/local/$groupId/users/$userId/remove`
* `POST /groups/$groupId/renew_attestation/$userId`
* `POST /groups/$groupId/summary/rooms/$roomId`
* `POST /groups/$groupId/summary/categories/$category/rooms/$roomId`
* `DELETE /groups/$groupId/summary/rooms/$roomId`
* `DELETE /groups/$groupId/summary/categories/$category/rooms/$roomId`
* `GET /groups/$groupdId/categories`
* `GET /groups/$groupId/categories/$category`
* `POST /groups/$groupId/categories/$category`
* `DELETE /groups/$groupId/categories/$category`
* `GET /groups/$groupId/roles`
* `GET /groups/$groupId/roles/$roleId`
* `POST /groups/$groupId/roles/$roleId`
* `DELETE /groups/$groupId/roles/$roleId`
* `POST /groups/$groupId/summary/users/$userId`
* `POST /groups/$groupId/summary/roles/$roleId/users/$userId`
* `DELETE /groups/$groupId/summary/users/$userId`
* `DELETE /groups/$groupId/summary/roles/$roleId/users/$userId`
* `POST /get_groups_publicised`
* `PUT /groups/$groupId/settings/m.join_policy`

**Comment by ptman** [comment]
#1215 replaced by #1772

**Comment by turt2live** [comment]
I'm declaring this as obsolete now that [MSC1772](https://github.com/matrix-org/matrix-doc/issues/1772) (Spaces, or Communities v2, or Groups v2) is in FCP. We anticipate that Spaces will take over the spec, and that Groups will never make it into an official spec document.
