### ISSUE TITLE
Grammar

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#1514]
This issue tracks everything related to grammer.

* [ ] https://github.com/matrix-org/matrix-doc/issues/1257 - device IDs
* [ ] #666 - opaque IDs
* [ ] #668 - aliases
* [ ] #667 - room IDs and event IDs
* [ ] #669 - disambiguation and display names

**Comment by neilisfragile** [comment]
MSC #1597 covers #666, #667, #1190 and #1257.
