### ISSUE TITLE
Push rules

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#1515]
This issue tracks all push rules related issues.

* [x] https://github.com/matrix-org/matrix-doc/issues/676 - new rules are enabled - https://github.com/matrix-org/matrix-doc/pull/1551
* [x] https://github.com/matrix-org/matrix-doc/issues/1034 - unrecognized rules - https://github.com/matrix-org/matrix-doc/pull/1551
* [x] https://github.com/matrix-org/matrix-doc/issues/1163 - missing rules from spec - https://github.com/matrix-org/matrix-doc/pull/1551
* ~~https://github.com/matrix-org/matrix-doc/issues/1164 - new level?~~ not applicable
* [x] https://github.com/matrix-org/matrix-doc/issues/1165 - confusing priorities - https://github.com/matrix-org/matrix-doc/pull/1551
