### ISSUE TITLE
Meta bug for edge cases that should be considered to make room upgrades transparent

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-doc#1942]
* [ ] Room membership (for public rooms) #1941 
* [ ] Room membership (for private rooms) #1941 (and #1864)
* [ ] Telling users about the new room if we are not yet  syncing room membership (#1930)
* [ ] Arbitrary room state #1940, #1872
  * it's unclear whether it's sufficient for the upgrading user to be able to re-create the state on behalf of the original users, or if we should get the original servers to re-create the state.  Presumably if we did the latter, then we could solve #1941 too?
* [ ] Specific room state?  (If we're not supporting arbitrary room state)
  * [ ] What flair is enabled for a room
  * [ ] What widgets are provisioned in a room
  * [ ] Power levels
    * [x] Bans  https://github.com/matrix-org/synapse/pull/4642
  * [x] Federatability  https://github.com/matrix-org/synapse/pull/4530
  * [x] Server ACLs https://github.com/matrix-org/synapse/pull/4642
  * [x] Encryption https://github.com/matrix-org/synapse/pull/4411
* [x] Tag state https://github.com/matrix-org/synapse/pull/4412
* [ ] Room directory entries https://github.com/matrix-org/synapse/issues/4948
* [x] Per-room push rules https://github.com/matrix-org/synapse/pull/4838
* [ ] Community membership (i.e. which rooms exist in a given community)
* [ ] Making bridges and bots and integrations in general upgrade-aware (e.g. https://github.com/matrix-org/matrix-appservice-bridge/pull/100)

At the least, we should ensure the spec reminds implementors to handle all these edge cases...

**Comment by richvdh** [comment]
see also: https://github.com/matrix-org/synapse/labels/type%3Aroomupgrades

**Comment by richvdh** [comment]
>  Arbitrary room state #1940, #1872

Neither #1940 nor #1872 appear to be "copy all state over by default", which is what I think you mean here?

**Comment by julianfoad** [comment]
See also
https://github.com/vector-im/riot-ios/issues/2486
https://github.com/vector-im/riot-android/issues/3186

**Comment by anoadragon453** [comment]
Curious if these two issues are solved by client-side behaviour now, or if that's not considered the ideal end goal:

> - Room membership (for public rooms) #1941
> - Room membership (for private rooms) #1941 (and #1864)

**Comment by Half-Shot** [comment]
I have nothing specific to add here, other than a datapoint that we upgraded a lot of rooms within a space today and it was a very painful experience to copy state over. A lot of the bots I tend to use in EMS-land use room state for configuration, and it doesn't feel like the bots should be responsible for copying that state over.

**Comment by clokep** [comment]
matrix-org/synapse#10774 made upgrading a space possible, which seems like it should be mentioned somewhere here. 😄

**Comment by dkasak** [comment]
Regarding carrying over arbitrary room state, there seemed to be some consensus that it was the way to go yesterday ([discussion](https://matrix.to/#/!kxwQeJPhRigXSZrHqf:matrix.org/$HbmpsIPNuGrJ6kaxHPlQQwcQxsPz_01EG4LbeDfW6ic?via=matrix.org&via=vector.modular.im&via=termina.org.uk)), but two points were raised:

- There'd be no way to have a room upgrade into a clean slate. This would be solved neatly by #1940.
- More specifically, we might want to retain the ability to drop `m.room.member == leave` state. This could be either special-cased or again incorporated into the mechanism suggested by #1940.
