### ISSUE TITLE
Placeholder for PRs regarding identity spec

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#2253]
This is just a tracking issue for myself, and maybe people who review the PRs.

High level PRs:
* [x] https://github.com/matrix-org/matrix-doc/pull/2254 - Mirror v1 to v2 where behaviour is unchanged (aside from auth). Covers part of [MSC2140](https://github.com/matrix-org/matrix-doc/pull/2140).
* [x] https://github.com/matrix-org/matrix-doc/pull/2255 - Actually define auth for identity servers. Covers part of [MSC2140](https://github.com/matrix-org/matrix-doc/pull/2140). Refer to [MSC1961](https://github.com/matrix-org/matrix-doc/pull/1961) (excl) when in doubt.
* [x] https://github.com/matrix-org/matrix-doc/pull/2258 - Define terms of service handling. Covers part of [MSC2140](https://github.com/matrix-org/matrix-doc/pull/2140). Will probably be based upon PR2, and might be best to just merge them together.
* [x] https://github.com/matrix-org/matrix-doc/pull/2279 - Remove `bind_msisdn` and `bind_email` from `/register`. Covers part of [MSC2140](https://github.com/matrix-org/matrix-doc/pull/2140).
* [x] https://github.com/matrix-org/matrix-doc/pull/2282 - Define new unbind endpoint and behaviour from [MSC2140](https://github.com/matrix-org/matrix-doc/pull/2140) (last 2140).
* [x] https://github.com/matrix-org/matrix-doc/pull/2281 - Introduce storing IS in account data. Covers [MSC2230](https://github.com/matrix-org/matrix-doc/pull/2230) (excl).
* [x] https://github.com/matrix-org/matrix-doc/pull/2287 - Introduce new lookup endpoint. Covers [MSC2134](https://github.com/matrix-org/matrix-doc/pull/2134) (excl).
* [x] https://github.com/matrix-org/matrix-doc/pull/2310 - Deprecate `id_server` in `requestToken`. Covers [MSC2263](https://github.com/matrix-org/matrix-doc/pull/2263) (excl).
* [x] https://github.com/matrix-org/matrix-doc/pull/2304 - Fix `isvalid` (and other v2) references for third party invites, etc
* [x] https://github.com/matrix-org/matrix-doc/pull/2328 - Add new add/bind endpoints for 3PIDs. Covers [MSC2290](https://github.com/matrix-org/matrix-doc/pull/2290) (excl).

*Note*: [MSC2264](https://github.com/matrix-org/matrix-doc/pull/2264) (excl) requires no spec changes.

**Comment by turt2live** [comment]
The remainder of this is blocked until 2290 decides if it is obsoletes 2263 or not.

**Comment by turt2live** [comment]
2290 has decided that 2263 is fine, so this is unblocked again.

**Comment by turt2live** [comment]
This now has all spec PRs open/merged - closing as this tracker is not needed anymore.
